/* Lógico: */

CREATE TABLE CARROS (
    CAR_ID INTEGER PRIMARY KEY,
    CAR_PLACA VARCHAR(10),
    CAR_COR VARCHAR(30),
    CAR_ANO INTEGER,
    CAR_PORTE VARCHAR(20),
    CAR_TIPO_CARGA VARCHAR(30),
    CAR_CHASSIS VARCHAR(17),
    FK_MODELOS_MOD_ID INTEGER,
    UNIQUE (CAR_CHASSIS, CAR_PLACA)
);

CREATE TABLE MARCAS (
    MAR_ID INTEGER PRIMARY KEY,
    MAR_NOME VARCHAR(50)
);

CREATE TABLE MODELOS (
    MOD_ID INTEGER PRIMARY KEY,
    MOD_NOME VARCHAR(50),
    FK_MARCAS_MAR_ID INTEGER
);
 
ALTER TABLE CARROS ADD CONSTRAINT FK_CARROS_2
    FOREIGN KEY (FK_MODELOS_MOD_ID)
    REFERENCES MODELOS (MOD_ID)
    ON DELETE CASCADE;
 
ALTER TABLE MODELOS ADD CONSTRAINT FK_MODELOS_2
    FOREIGN KEY (FK_MARCAS_MAR_ID)
    REFERENCES MARCAS (MAR_ID)
    ON DELETE CASCADE;